[package]
name = "autodiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flame = "0.2.2"
flamer = "0.4.0"
nalgebra = { version = "0.32.2", features = ["rand"] }
